sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker
  - mysql
  - mongodb

script:
  - set -e
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('testtest') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - echo "USE mysql;\nCREATE DATABASE trading-test;\n" | mysql -u root -p testtest
  - mysql -u root -p testtest --default-character-set=utf8 trading-test < trading-persistence/src/main/resources/mysql/20180421-00-Initial-Account.sql
  - docker ps
  - ./gradlew build
